<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <AssemblyName>carsim</AssemblyName>
    <RootNamespace>CarSim.Cli</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\CarSim.Core\CarSim.Core.csproj" />
    <ProjectReference Include="..\..\src\CarSim.Gameplay\CarSim.Gameplay.csproj" />
  </ItemGroup>
</Project>
