using System.Globalization;
using System.Text;

namespace CarSim.Verification.Fingerprint;

/// <summary>
/// The checked-in regression fingerprint (<c>tests/baselines/fingerprint.txt</c>). Line-oriented, sorted and stable so
/// a re-baseline reads as a diff:
/// <code>
/// schema &lt;channel&gt;                                        channels digested (one per line)
/// case &lt;id&gt; &lt;description&gt;
/// digest &lt;case&gt; &lt;section&gt; &lt;sha256&gt; samples=&lt;n&gt; channels=&lt;m&gt;
/// value &lt;case&gt; &lt;section&gt; &lt;name&gt; &lt;value&gt;                  full precision, readable
/// </code>
/// A section's digest covers every value of every schema channel it recorded, in order, plus its key numbers; channels
/// added by later code are left out of the digest and reported, so adding telemetry does not break the baseline while
/// any change to an existing channel does.
/// </summary>
public sealed class FingerprintBaseline
{
    public const string Header = "# CarSim regression fingerprint v1 — generated by `carsim fingerprint --write`; do not edit by hand.";

    public SortedSet<string> Schema { get; } = new(StringComparer.Ordinal);
    public Dictionary<string, string> Descriptions { get; } = new(StringComparer.Ordinal);

    /// <summary>(case, section) → the section as recorded.</summary>
    public Dictionary<(string Case, string Section), SectionRecord> Sections { get; } = new();

    /// <summary>Sections in the order they were recorded (cases in matrix order, sections in run order).</summary>
    public List<(string Case, string Section)> Order { get; } = new();

    private void Add(string caseId, SectionRecord section)
    {
        if (Sections.TryAdd((caseId, section.Name), section)) Order.Add((caseId, section.Name));
        else throw new InvalidOperationException($"Duplicate section {caseId}/{section.Name}.");
    }

    public IEnumerable<string> CaseIds => Descriptions.Keys;

    public static FingerprintBaseline FromRecords(IEnumerable<(FingerprintCase Case, CaseRecord Record)> records)
    {
        var b = new FingerprintBaseline();
        foreach (var (c, record) in records)
        {
            b.Descriptions[c.Id] = c.Description;
            foreach (var ch in record.Channels) b.Schema.Add(ch);
            foreach (var s in record.Sections) b.Add(c.Id, s);
        }
        return b;
    }

    public string ToText(IReadOnlyList<string> caseOrder)
    {
        var sb = new StringBuilder();
        sb.AppendLine(Header);
        sb.AppendLine("# Platform: linux-x64, .NET 8 (IEEE-754 doubles; libm from the OS). See docs/VERIFICATION.md.");
        foreach (var ch in Schema) sb.Append("schema ").AppendLine(ch);
        foreach (var id in caseOrder.Where(Descriptions.ContainsKey))
        {
            sb.Append("case ").Append(id).Append(' ').AppendLine(Descriptions[id]);
            foreach (var key in Order.Where(k => k.Case == id))
            {
                var (caseId, s) = (key.Case, Sections[key]);
                sb.Append(CultureInfo.InvariantCulture, $"digest {caseId} {s.Name} {s.Digest} samples={s.Samples} channels={s.ChannelCount}").AppendLine();
                foreach (var (name, value) in s.Values)
                    sb.Append(CultureInfo.InvariantCulture, $"value {caseId} {s.Name} {name} {value}").AppendLine();
            }
        }
        return sb.ToString();
    }

    public static FingerprintBaseline Parse(string text)
    {
        var b = new FingerprintBaseline();
        int lineNo = 0;
        foreach (var raw in text.Split('\n'))
        {
            lineNo++;
            string line = raw.TrimEnd('\r');
            if (line.Length == 0 || line.StartsWith('#')) continue;
            var parts = line.Split(' ', 5);
            switch (parts[0])
            {
                case "schema":
                    b.Schema.Add(line["schema ".Length..]);
                    break;
                case "case":
                    var c = line["case ".Length..].Split(' ', 2);
                    b.Descriptions[c[0]] = c.Length > 1 ? c[1] : "";
                    break;
                case "digest" when parts.Length >= 5:
                    var tail = parts[4].Split(' ');
                    var section = new SectionRecord(parts[2])
                    {
                        Digest = parts[3],
                        Samples = int.Parse(tail.Single(t => t.StartsWith("samples=", StringComparison.Ordinal))["samples=".Length..], CultureInfo.InvariantCulture),
                        ChannelCount = int.Parse(tail.Single(t => t.StartsWith("channels=", StringComparison.Ordinal))["channels=".Length..], CultureInfo.InvariantCulture),
                    };
                    b.Add(parts[1], section);
                    break;
                case "value" when parts.Length >= 4:
                    var v = line.Split(' ', 5);
                    b.Sections[(v[1], v[2])].Values.Add(new(v[3], v.Length > 4 ? v[4] : ""));
                    break;
                default:
                    throw new FormatException($"fingerprint baseline line {lineNo}: '{line}'");
            }
        }
        return b;
    }

    public static FingerprintBaseline Load(string path) => Parse(File.ReadAllText(path));
}

/// <summary>How a run compares with the baseline.</summary>
public sealed class FingerprintComparison
{
    /// <summary>Sections whose digest differs, with the key numbers that moved.</summary>
    public List<string> Changed { get; } = new();

    /// <summary>Sections in the baseline the run did not produce, or produced without some of the baseline's channels.</summary>
    public List<string> Missing { get; } = new();

    /// <summary>Channels the run produced that the baseline's schema does not have (informational).</summary>
    public List<string> NewChannels { get; } = new();

    public bool Identical => Changed.Count == 0 && Missing.Count == 0;

    public static FingerprintComparison Compare(FingerprintBaseline baseline, IEnumerable<CaseRecord> run)
    {
        var result = new FingerprintComparison();
        var seen = new SortedSet<string>(StringComparer.Ordinal);
        foreach (var record in run)
        {
            foreach (var ch in record.Channels) seen.Add(ch);
            var produced = record.Sections.ToDictionary(s => s.Name, StringComparer.Ordinal);
            foreach (var (caseId, name) in baseline.Order.Where(k => k.Case == record.CaseId))
            {
                var expected = baseline.Sections[(caseId, name)];
                if (!produced.TryGetValue(name, out var actual))
                {
                    result.Missing.Add($"{caseId}/{name}: section not produced");
                    continue;
                }
                if (actual.ChannelCount < expected.ChannelCount || actual.Samples != expected.Samples)
                    result.Missing.Add($"{caseId}/{name}: {actual.Samples} samples × {actual.ChannelCount} channels, baseline {expected.Samples} × {expected.ChannelCount}");
                if (actual.Digest != expected.Digest)
                    result.Changed.Add(Describe(caseId, name, expected, actual));
            }
            foreach (var s in record.Sections.Where(s => !baseline.Sections.ContainsKey((record.CaseId, s.Name))))
                result.Missing.Add($"{record.CaseId}/{s.Name}: not in the baseline");
        }
        result.NewChannels.AddRange(seen.Where(ch => !baseline.Schema.Contains(ch)));
        return result;
    }

    private static string Describe(string caseId, string section, SectionRecord expected, SectionRecord actual)
    {
        var sb = new StringBuilder($"{caseId}/{section}: digest {expected.Digest[..12]} → {actual.Digest[..12]}");
        var now = actual.Values.GroupBy(v => v.Key).ToDictionary(g => g.Key, g => g.First().Value, StringComparer.Ordinal);
        int shown = 0, moved = 0;
        foreach (var (name, was) in expected.Values)
        {
            if (!now.TryGetValue(name, out var value) || value == was) continue;
            moved++;
            if (shown++ >= 12) continue;
            sb.Append("\n    ").Append(name).Append(": ").Append(was).Append(" → ").Append(value);
            if (double.TryParse(was, NumberStyles.Float, CultureInfo.InvariantCulture, out double a)
                && double.TryParse(value, NumberStyles.Float, CultureInfo.InvariantCulture, out double b) && a != 0)
                sb.Append(CultureInfo.InvariantCulture, $" ({(b - a) / Math.Abs(a) * 100:+0.0000;-0.0000}%)");
        }
        if (moved > shown) sb.Append(CultureInfo.InvariantCulture, $"\n    … {moved - shown} more key numbers moved");
        if (moved == 0) sb.Append("\n    (no key number moved: the change is in the sampled channels; use `carsim fingerprint --dump` on both commits and `carsim fingerprint-diff`)");
        return sb.ToString();
    }
}
