using CarSim.Core.Content;
using CarSim.Verification;
using CarSim.Verification.Calibration;

namespace CarSim.Core.Tests.Verification;

/// <summary>
/// The recalibration driver's manifest and file writer (docs/VERIFICATION.md, "Tune regeneration"). The driver's output
/// itself is pinned by the fingerprint case <c>k20_regen_stock_ve</c>; here: every tune has exactly one recipe, recipes
/// never write a hand-authored table, and writing a tune's own values back leaves its file byte-identical — so a
/// regeneration diff only ever shows the values that moved.
/// </summary>
public class TuneRegenerationTests
{
    private static readonly TuneManifest Manifest = TuneManifest.Load(RepoPaths.TuneManifest);

    [Fact]
    public void EveryShippedAndTestTuneHasExactlyOneRecipe()
    {
        var db = TestContent.Matrix;
        Assert.Equal(db.Tunes.Keys.OrderBy(k => k, StringComparer.Ordinal), Manifest.Tunes.Select(t => t.Tune).OrderBy(k => k, StringComparer.Ordinal));
        foreach (var recipe in Manifest.Tunes)
        {
            // The recipe's engine exists; a family's stock tune is calibrated on that family (extra tunes, like the K20 turbo
            // base map, name the family whose build they were measured on).
            Assert.NotNull(db.GetEngine(recipe.Engine));
            foreach (var family in db.Engines.Values.Where(e => e.StockTune == recipe.Tune)) Assert.Equal(family.Id, recipe.Engine);
            Assert.NotNull(db.GetFuel(recipe.Fuel));
            Assert.Equal(recipe.Layer == "test", !TestContent.Database.Tunes.ContainsKey(recipe.Tune));
            Assert.Contains($"\"{recipe.Tune}\"", File.ReadAllText(Path.Combine(TestContent.RepoRoot, recipe.File)));
            Assert.NotEmpty(recipe.Steps);
            Assert.False(string.IsNullOrWhiteSpace(recipe.Provenance));
        }
    }

    [Fact]
    public void RecipesNeverWriteAHandAuthoredTable()
    {
        foreach (var recipe in Manifest.Tunes)
        {
            var written = recipe.Steps.Select(s => TuneRegenerator.FieldOf(s.Calibrator)).ToHashSet();
            Assert.Empty(written.Intersect(recipe.HandAuthored));
            // A table that is neither calibrated nor declared hand-authored would be regenerated by nobody and audited by nobody.
            foreach (var table in new[] { "target_lambda", "ignition_advance_deg", "volumetric_efficiency" })
                Assert.True(written.Contains(table) || recipe.HandAuthored.Contains(table), $"{recipe.Tune}: '{table}' has no rule");
        }
    }

    [Fact]
    public void EveryTuneFileRoundTripsThroughTheWriter()
    {
        foreach (var recipe in Manifest.Tunes)
            Assert.True(TuneRegenerator.FileRoundTrips(recipe, TestContent.RepoRoot), $"{recipe.File}: writing {recipe.Tune}'s own values back changes the file");
    }

    [Fact]
    public void TheWriterReplacesOnlyTheCalibratedTable()
    {
        var recipe = Manifest.Tunes.Single(t => t.Tune == "m54.stock");
        string path = Path.Combine(TestContent.RepoRoot, recipe.File);
        string text = File.ReadAllText(path);
        var doc = TestContent.Database.GetTune(recipe.Tune);
        var ve = doc.VolumetricEfficiency!.Select(row => row.Select(v => Math.Round(v + 0.001, 3)).ToArray()).ToArray();
        string written = TuneRegenerator.Write(text, recipe.Tune, doc with { VolumetricEfficiency = ve }, new[] { TuneRegenerator.VolumetricEfficiency });

        var reloaded = ContentLoader.LoadFromStrings(new[] { (recipe.File, written) }).Database.GetTune(recipe.Tune);
        Assert.Equal(ve, reloaded.VolumetricEfficiency);
        Assert.Equal(doc.IgnitionAdvanceDeg, reloaded.IgnitionAdvanceDeg);
        Assert.Equal(doc.IntakeCamAdvanceDeg, reloaded.IntakeCamAdvanceDeg);
        // Only the rows of the table changed: the same number of lines, and every differing line is a VE row.
        var before = text.Split('\n');
        var after = written.Split('\n');
        Assert.Equal(before.Length, after.Length);
        var changed = before.Zip(after).Where(p => p.First != p.Second).ToList();
        Assert.Equal(ve.Length, changed.Count);
    }
}
