using CarSim.Core.Content;
using CarSim.Verification;
using CarSim.Verification.Calibration;

namespace CarSim.Core.Tests.Verification;

/// <summary>
/// The recalibration driver's manifest and file writer (docs/VERIFICATION.md, "Tune regeneration"). The driver's output
/// itself is pinned by the fingerprint case <c>k20_regen_stock_ve</c>; here: every tune has exactly one recipe, recipes
/// never write a hand-authored table, and writing a tune's own values back leaves its file byte-identical — so a
/// regeneration diff only ever shows the values that moved.
/// </summary>
public class TuneRegenerationTests
{
    private static readonly TuneManifest Manifest = TuneManifest.Load(RepoPaths.TuneManifest);

    [Fact]
    public void EveryShippedAndTestTuneHasExactlyOneRecipe()
    {
        var db = TestContent.Matrix;
        Assert.Equal(db.Tunes.Keys.OrderBy(k => k, StringComparer.Ordinal), Manifest.Tunes.Select(t => t.Tune).OrderBy(k => k, StringComparer.Ordinal));
        foreach (var recipe in Manifest.Tunes)
        {
            // The recipe's engine exists; a family's stock tune is calibrated on that family (extra tunes, like the K20 turbo
            // base map, name the family whose build they were measured on).
            Assert.NotNull(db.GetEngine(recipe.Engine));
            foreach (var family in db.Engines.Values.Where(e => e.StockTune == recipe.Tune)) Assert.Equal(family.Id, recipe.Engine);
            Assert.NotNull(db.GetFuel(recipe.Fuel));
            Assert.Equal(recipe.Layer == "test", !TestContent.Database.Tunes.ContainsKey(recipe.Tune));
            Assert.Contains($"\"{recipe.Tune}\"", File.ReadAllText(Path.Combine(TestContent.RepoRoot, recipe.File)));
            Assert.NotEmpty(recipe.Steps);
            Assert.False(string.IsNullOrWhiteSpace(recipe.Provenance));
        }
    }

    [Fact]
    public void RecipesNeverWriteAHandAuthoredTable()
    {
        foreach (var recipe in Manifest.Tunes)
        {
            var written = recipe.Steps.Select(s => TuneRegenerator.FieldOf(s.Calibrator)).ToHashSet();
            Assert.Empty(written.Intersect(recipe.HandAuthored));
            // A table that is neither calibrated nor declared hand-authored would be regenerated by nobody and audited by nobody.
            foreach (var table in new[] { "target_lambda", "ignition_advance_deg", "volumetric_efficiency" })
                Assert.True(written.Contains(table) || recipe.HandAuthored.Contains(table), $"{recipe.Tune}: '{table}' has no rule");
        }
    }

    /// <summary>
    /// The hardware schedule (cam phase, stage switch speeds) is set before the maps measured on it: a switch speed moved
    /// after the fuel map leaves the VE cells between the old and the new speed measured on the other stage (syn.r6 before
    /// the 2026-09-27 regeneration: up to 0.021 VE on a second pass).
    /// </summary>
    [Fact]
    public void RecipesSetTheHardwareScheduleBeforeTheMapsMeasuredOnIt()
    {
        string[] schedule = { "cams", "runner_switch", "lift_switch" };
        foreach (var recipe in Manifest.Tunes)
        {
            var steps = recipe.Steps.Select(s => s.Calibrator).ToList();
            int lastSchedule = steps.FindLastIndex(schedule.Contains), firstMap = steps.FindIndex(s => !schedule.Contains(s));
            Assert.True(lastSchedule < firstMap || lastSchedule < 0, $"{recipe.Tune}: {string.Join(" → ", steps)}");
        }
    }

    /// <summary>
    /// A regeneration writes only values that settle: a cell the second pass returns to its checked-in value is a rounding
    /// 2-cycle and keeps it; a cell that settles on a new value takes it; one that moves again is reported unsettled.
    /// </summary>
    [Fact]
    public void RoundingTwoCyclesKeepTheirCheckedInValue()
    {
        double[][] checkedIn = { new[] { 16.0, 21.5, 10.0, 8.0 } };
        double[][] first = { new[] { 15.5, 21.5, 11.0, 9.0 } };
        double[][] second = { new[] { 16.0, 21.0, 11.0, 9.5 } };
        var settled = TuneRegenerator.SettleTwoCycles(checkedIn, first, second, out int oscillating, out int unsettled);
        // 16 → 15.5 → 16: 2-cycle, kept. 21.5 unchanged on the first pass: kept. 10 → 11 → 11: settled, written.
        // 8 → 9 → 9.5: moved again, the first pass's value is written and reported.
        Assert.Equal(new[] { 16.0, 21.5, 11.0, 9.0 }, settled[0]);
        Assert.Equal(1, oscillating);
        Assert.Equal(1, unsettled);
    }

    [Fact]
    public void EveryTuneFileRoundTripsThroughTheWriter()
    {
        foreach (var recipe in Manifest.Tunes)
            Assert.True(TuneRegenerator.FileRoundTrips(recipe, TestContent.RepoRoot), $"{recipe.File}: writing {recipe.Tune}'s own values back changes the file");
    }

    [Fact]
    public void TheWriterReplacesOnlyTheCalibratedTable()
    {
        var recipe = Manifest.Tunes.Single(t => t.Tune == "m54.stock");
        string path = Path.Combine(TestContent.RepoRoot, recipe.File);
        string text = File.ReadAllText(path);
        var doc = TestContent.Database.GetTune(recipe.Tune);
        var ve = doc.VolumetricEfficiency!.Select(row => row.Select(v => Math.Round(v + 0.001, 3)).ToArray()).ToArray();
        string written = TuneRegenerator.Write(text, recipe.Tune, doc with { VolumetricEfficiency = ve }, new[] { TuneRegenerator.VolumetricEfficiency });

        var reloaded = ContentLoader.LoadFromStrings(new[] { (recipe.File, written) }).Database.GetTune(recipe.Tune);
        Assert.Equal(ve, reloaded.VolumetricEfficiency);
        Assert.Equal(doc.IgnitionAdvanceDeg, reloaded.IgnitionAdvanceDeg);
        Assert.Equal(doc.IntakeCamAdvanceDeg, reloaded.IntakeCamAdvanceDeg);
        // Only the rows of the table changed: the same number of lines, and every differing line is a VE row.
        var before = text.Split('\n');
        var after = written.Split('\n');
        Assert.Equal(before.Length, after.Length);
        var changed = before.Zip(after).Where(p => p.First != p.Second).ToList();
        Assert.Equal(ve.Length, changed.Count);
    }
}
